/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jproject1;
    import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class AddCT extends javax.swing.JFrame {

    /**
     * Creates new form AddCT
     */
    public AddCT() {
        initComponents();
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jproject1","root","");
            
            String q="select * from addstudent";
            
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(q);
            
            while(rs.next())
            {
                c1.addItem(rs.getString("RollNo"));
            }
                
                con.close();
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Add CT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Roll Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Branch");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Semester");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("CT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Subject Names");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Marks");

        b2.setBackground(new java.awt.Color(0, 0, 102));
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("Save");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(0, 0, 102));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("Cancel");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        c2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        b1.setBackground(new java.awt.Color(0, 0, 102));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("Go");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });

        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });

        t3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });

        t4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });

        t5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });

        t6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t6KeyTyped(evt);
            }
        });

        t7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t7KeyTyped(evt);
            }
        });

        t8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t8KeyTyped(evt);
            }
        });

        t9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t9KeyTyped(evt);
            }
        });

        t10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t10KeyTyped(evt);
            }
        });

        t11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t11KeyTyped(evt);
            }
        });

        t12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t12KeyTyped(evt);
            }
        });

        t14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        t13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(b1)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b3)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2)
                            .addComponent(t4)
                            .addComponent(t6)
                            .addComponent(t8)
                            .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c2)
                    .addComponent(t13)
                    .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3)
                    .addComponent(b2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String rollno=c1.getSelectedItem().toString();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jproject1","root","");
            
            String q="select * from addstudent where RollNo='"+rollno+"'";
            
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(q);
            
            while(rs.next())
            {
                t13.setText(rs.getString("Branch"));
                t14.setText(rs.getString("Semester"));
                
                String branch=rs.getString("Branch");
                String sem=rs.getString("Semester");
                
                if(branch.equalsIgnoreCase("CSE"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemistry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("C");
                        t3.setText("Basic Electronics");
                        t5.setText("DELD");
                        t7.setText("Applied Mathematics-3");
                        t9.setText("CS");
                        t11.setText("CCWT");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("OOP");
                        t3.setText("Data Structures");
                        t5.setText("CSA");
                        t7.setText("Computational Mathematics");
                        t9.setText("Operating System");
                        t11.setText("Discrete Structures");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("DBMS");
                        t3.setText("TOC");
                        t5.setText("ADA");
                        t7.setText("Micro-Processor");
                        t9.setText("JAVA");
                        t11.setText("Unix");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
                if(branch.equalsIgnoreCase("IT"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemestry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
                if(branch.equalsIgnoreCase("ETC"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemestry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
                if(branch.equalsIgnoreCase("EEE"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemestry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
                if(branch.equalsIgnoreCase("EE"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemestry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
                if(branch.equalsIgnoreCase("Mech"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemestry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
                if(branch.equalsIgnoreCase("Civil"))
                {
                    if(sem.equals("1st"))
                    {
                        t1.setText("Engineering Graphics");
                        t3.setText("Applied Chemestry");
                        t5.setText("EEE");
                        t7.setText("Applied Mathematics-1");
                        t9.setText("Communication in English");
                        t11.setText("");
                    }
                    if(sem.equals("2nd"))
                    {
                        t1.setText("FME");
                        t3.setText("Applied Physics");
                        t5.setText("Basic Civil");
                        t7.setText("Applied Mathematics-2");
                        t9.setText("EE");
                        t11.setText("");
                    }
                    if(sem.equals("3rd"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("4th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("5th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("6th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("7th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                    if(sem.equals("8th"))
                    {
                        t1.setText("");
                        t3.setText("");
                        t5.setText("");
                        t7.setText("");
                        t9.setText("");
                        t11.setText("");
                    }
                }
            }
            
            con.close();
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            t6.setText("");
            t7.setText("");
            t8.setText("");
            t9.setText("");
            t10.setText("");
            t11.setText("");
            t12.setText("");
            t13.setText("");
            t14.setText("");
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String rollno=c1.getSelectedItem().toString();
            String branch=t13.getText();
            String semester=t14.getText();
            String ctno=c2.getSelectedItem().toString();
            String s1=t1.getText();
            String m1=t2.getText();
            int mark1=Integer.parseInt(m1);
            String s2=t3.getText();
            String m2=t4.getText();
            int mark2=Integer.parseInt(m2);
            String s3=t5.getText();
            String m3=t6.getText();
            int mark3=Integer.parseInt(m3);
            String s4=t7.getText();
            String m4=t8.getText();
            int mark4=Integer.parseInt(m4);
            String s5=t9.getText();
            String m5=t10.getText();
            int mark5=Integer.parseInt(m5);
            String s6=t11.getText();
            String m6=t12.getText();
            int mark6=Integer.parseInt(m6);
            
            int t=mark1+mark2+mark3+mark4+mark5+mark6;
            String total=t+"";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jproject1","root","");
            
            String q1="select * from addct where RollNo='"+rollno+"'";
            Statement stmt1=con.createStatement();
            ResultSet rs1=stmt1.executeQuery(q1);
            
            if(rs1.next())
            {
                JOptionPane.showMessageDialog(null,"Roll Number already available.....");
            }
            else
            {
                String q2="insert into addct values('"+rollno+"','"+branch+"','"+semester+"','"+ctno+"','"+s1+"','"+m1+"','"+s2+"','"+m2+"','"+s3+"','"+m3+"','"+s4+"','"+m4+"','"+s5+"','"+m5+"','"+s6+"','"+m6+"','"+total+"')";
            
                Statement stmt2=con.createStatement();
                int rs2=stmt2.executeUpdate(q2);
            
                if(rs2!=0)
                {
                    System.out.println("Saved");
                }
            }
            con.close();
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t1KeyTyped

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t3KeyTyped

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t5KeyTyped

    private void t7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t7KeyTyped

    private void t9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t9KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t9KeyTyped

    private void t11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t11KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t11KeyTyped

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=47 || c>=58 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t2KeyTyped

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=47 || c>=58 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t4KeyTyped

    private void t6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=47 || c>=58 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t6KeyTyped

    private void t8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=47 || c>=58 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t8KeyTyped

    private void t10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t10KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=47 || c>=58 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t10KeyTyped

    private void t12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t12KeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        
        if(c>=0 && c<=47 || c>=58 && c<=127)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t12KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
